call_method:
  target:
    entity:
      integration: squeezebox
      domain: media_player
  fields:
    command:
      required: true
      example: "playlist"
      selector:
        text:
    parameters:
      example: '["loadtracks", "album.titlesearch=Revolver"]'
      advanced: true
      selector:
        object:
call_query:
  target:
    entity:
      integration: squeezebox
      domain: media_player
  fields:
    command:
      required: true
      example: "albums"
      selector:
        text:
    parameters:
      example: '["0", "20", "search:Revolver"]'
      advanced: true
      selector:
        object:
search:
  fields:
    device_id:
      required: true
      selector:
        device:
          filter:
            - integration: squeezebox
              manufacturer: https://lyrion.org/
    command:
      required: true
      selector:
        select:
          translation_key: "search_command_selector"
          multiple: false
          options:
            - albums
            - artists
            - tracks
            - playlists
            - genres
            - favorites
            - players
    return_items:
      required: true
      selector:
        number:
          min: 1
          max: 10000
          mode: box
    search_string:
      required: false
      example: Revolver
      selector:
        text:
